Catalogue/Controllers/HockeysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Catalogue.DataBase;
using Catalogue.Models;

namespace Catalogue.Controllers
{
    public class HockeysController : Controller
    {
        private readonly CatalogueContext _context;

        public HockeysController(CatalogueContext context)
        {
            _context = context;
        }

        // GET: Hockeys
        public async Task<IActionResult> Index()
        {
              return _context.Hockeys != null ? 
                          View(await _context.Hockeys.ToListAsync()) :
                          Problem("Entity set 'CatalogueContext.Hockeys'  is null.");
        }

        // GET: Hockeys/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Hockeys == null)
            {
                return NotFound();
            }

            var hockey = await _context.Hockeys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hockey == null)
            {
                return NotFound();
            }

            return View(hockey);
        }

        // GET: Hockeys/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hockeys/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomProduit,Marque,Taille,QuantiteEnInventaire,Photo,Categorie,DescriptionDetaillee")] Hockey hockey)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hockey);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hockey);
        }

        // GET: Hockeys/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Hockeys == null)
            {
                return NotFound();
            }

            var hockey = await _context.Hockeys.FindAsync(id);
            if (hockey == null)
            {
                return NotFound();
            }
            return View(hockey);
        }

        // POST: Hockeys/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomProduit,Marque,Taille,QuantiteEnInventaire,Photo,Categorie,DescriptionDetaillee")] Hockey hockey)
        {
            if (id != hockey.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hockey);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HockeyExists(hockey.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hockey);
        }

        // GET: Hockeys/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Hockeys == null)
            {
                return NotFound();
            }

            var hockey = await _context.Hockeys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hockey == null)
            {
                return NotFound();
            }

            return View(hockey);
        }

        // POST: Hockeys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Hockeys == null)
            {
                return Problem("Entity set 'CatalogueContext.Hockeys'  is null.");
            }
            var hockey = await _context.Hockeys.FindAsync(id);
            if (hockey != null)
            {
                _context.Hockeys.Remove(hockey);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HockeyExists(int id)
        {
          return (_context.Hockeys?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Catalogue/Controllers/PaniersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Catalogue.DataBase;
using Catalogue.Models;

namespace Catalogue.Controllers
{
    public class PaniersController : Controller
    {
        private readonly CatalogueContext _context;

        public PaniersController(CatalogueContext context)
        {
            _context = context;
        }

        // GET: Paniers
        public async Task<IActionResult> Index()
        {
            var paniers = await _context.Paniers.ToListAsync();

            if (paniers == null)
            {
                return NotFound();
            }
            else { 
            }
            return View(paniers);
        }

        // GET: Paniers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Paniers == null)
            {
                return NotFound();
            }

            var panier = await _context.Paniers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (panier == null)
            {
                return NotFound();
            }

            return View(panier);
        }

        // GET: Paniers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Paniers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomProduit,Taille,QuantiteEnInventaire,Photo")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(panier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(panier);
        }

        // GET: Paniers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Paniers == null)
            {
                return NotFound();
            }

            var panier = await _context.Paniers.FindAsync(id);
            if (panier == null)
            {
                return NotFound();
            }
            return View(panier);
        }

        // POST: Paniers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomProduit,Taille,QuantiteEnInventaire,Photo")] Panier panier)
        {
            if (id != panier.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(panier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PanierExists(panier.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(panier);
        }

        // GET: Paniers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Paniers == null)
            {
                return NotFound();
            }

            var panier = await _context.Paniers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (panier == null)
            {
                return NotFound();
            }

            return View(panier);
        }

        // POST: Paniers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Paniers == null)
            {
                return Problem("Entity set 'CatalogueContext.Paniers'  is null.");
            }
            var panier = await _context.Paniers.FindAsync(id);
            if (panier != null)
            {
                _context.Paniers.Remove(panier);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PanierExists(int id)
        {
          return (_context.Paniers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Catalogue/Controllers/VelosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Catalogue.DataBase;
using Catalogue.Models;

namespace Catalogue.Controllers
{
    public class VelosController : Controller
    {
        private readonly CatalogueContext _context;

        public VelosController(CatalogueContext context)
        {
            _context = context;
        }

        // GET: Veloes
        public async Task<IActionResult> Index()
        {
              return _context.Velos != null ? 
                          View(await _context.Velos.ToListAsync()) :
                          Problem("Entity set 'CatalogueContext.Velos'  is null.");
        }

        // GET: Veloes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Velos == null)
            {
                return NotFound();
            }

            var velo = await _context.Velos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (velo == null)
            {
                return NotFound();
            }

            return View(velo);
        }

        // GET: Veloes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Veloes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomProduit,Marque,Taille,QuantiteEnInventaire,Photo,Categorie,DescriptionDetaillee")] Velo velo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(velo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(velo);
        }

        // GET: Veloes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Velos == null)
            {
                return NotFound();
            }

            var velo = await _context.Velos.FindAsync(id);
            if (velo == null)
            {
                return NotFound();
            }
            return View(velo);
        }

        // POST: Veloes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomProduit,Marque,Taille,QuantiteEnInventaire,Photo,Categorie,DescriptionDetaillee")] Velo velo)
        {
            if (id != velo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(velo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VeloExists(velo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(velo);
        }

        // GET: Veloes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Velos == null)
            {
                return NotFound();
            }

            var velo = await _context.Velos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (velo == null)
            {
                return NotFound();
            }

            return View(velo);
        }

        // POST: Veloes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Velos == null)
            {
                return Problem("Entity set 'CatalogueContext.Velos'  is null.");
            }
            var velo = await _context.Velos.FindAsync(id);
            if (velo != null)
            {
                _context.Velos.Remove(velo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VeloExists(int id)
        {
          return (_context.Velos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Catalogue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catalogue</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Catalogue.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/images/favicon.png"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                                Catalogue
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Hockeys" asp-action="Index">Hockey</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Baseballs" asp-action="Index">Baseball</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Soccers" asp-action="Index">Soccer</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Velos" asp-action="Index">Vélo</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Catalogue" asp-action="Index">Tout</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paniers" asp-action="Index">Panier d’achats</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Commandes" asp-action="Privacy">Historique des commandes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Workshop">Télécharger Atelier</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Propos"> À propos</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Catalogue - <a asp-controller="Home" asp-action="Propos"> À propos</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>